/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mygradle

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    fun operation(a: Int, b: Int, calculate: (Int, Int) -> Int): Int {
        return calculate(a, b)
    }
}

fun main() {
    println(App().greeting)
}
