/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package unit.test.kotlin

import kotlin.test.*

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
