/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package features

import kotlin.test.Test
import kotlin.test.assertNotNull

class FeatureModuleTest {
    @Test fun testFeatureFunction() {
        val classUnderTest = FeatureModule()
        assertNotNull(classUnderTest.featureFunction(), "app should have a feature module function")
    }
}
